fetch non-public email and trust it.
julianlam/nodebb-plugin-sso-github pull request #5
Opened 2016-10-25 06:51 UTC by revir

2016-10-25 15:10 UTC, julianlam requested changes
Looks good, though certain files need to be reverted to their original state. Thanks!

2016-10-25 15:10 UTC, julianlam commented on README.md
> +
README can be reverted 😄

2016-10-25 15:10 UTC, julianlam commented on package.json
>    "readmeFilename": "README.md",
This file can be reverted too, though feel free to keep your name in `contributors` 😃

2016-10-25 15:10 UTC, julianlam commented on plugin.json
>  		{ "hook": "static:app.load", "method": "init" },
File can be reverted

2016-10-26 09:34 UTC, revir commented
sorry, I fixed the two problems, and then I wanted to use it on my website, so I changed the readme and package.json, and published to npm, I thought it won't conflict with yours. 
Maybe you can just merge with those previous two changes, and then I will delete my repo, could you?

2016-10-28 03:17 UTC, closed without merging